/*
 * Generated by gdbus-codegen 2.48.2. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifndef __SRC_MYAPP_GENERATED_H__
#define __SRC_MYAPP_GENERATED_H__

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for org.freedesktop.DBus.Introspection */

#define MY_EXAMPLE_TYPE_ORG_FREEDESKTOP_DBUS_INTROSPECTION (my_example_org_freedesktop_dbus_introspection_get_type ())
#define MY_EXAMPLE_ORG_FREEDESKTOP_DBUS_INTROSPECTION(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), MY_EXAMPLE_TYPE_ORG_FREEDESKTOP_DBUS_INTROSPECTION, MyExampleOrgFreedesktopDBusIntrospection))
#define MY_EXAMPLE_IS_ORG_FREEDESKTOP_DBUS_INTROSPECTION(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), MY_EXAMPLE_TYPE_ORG_FREEDESKTOP_DBUS_INTROSPECTION))
#define MY_EXAMPLE_ORG_FREEDESKTOP_DBUS_INTROSPECTION_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), MY_EXAMPLE_TYPE_ORG_FREEDESKTOP_DBUS_INTROSPECTION, MyExampleOrgFreedesktopDBusIntrospectionIface))

struct _MyExampleOrgFreedesktopDBusIntrospection;
typedef struct _MyExampleOrgFreedesktopDBusIntrospection MyExampleOrgFreedesktopDBusIntrospection;
typedef struct _MyExampleOrgFreedesktopDBusIntrospectionIface MyExampleOrgFreedesktopDBusIntrospectionIface;

struct _MyExampleOrgFreedesktopDBusIntrospectionIface
{
  GTypeInterface parent_iface;

  gboolean (*handle_introspect) (
    MyExampleOrgFreedesktopDBusIntrospection *object,
    GDBusMethodInvocation *invocation);

};

GType my_example_org_freedesktop_dbus_introspection_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *my_example_org_freedesktop_dbus_introspection_interface_info (void);
guint my_example_org_freedesktop_dbus_introspection_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void my_example_org_freedesktop_dbus_introspection_complete_introspect (
    MyExampleOrgFreedesktopDBusIntrospection *object,
    GDBusMethodInvocation *invocation,
    const gchar *data);



/* D-Bus method calls: */
void my_example_org_freedesktop_dbus_introspection_call_introspect (
    MyExampleOrgFreedesktopDBusIntrospection *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean my_example_org_freedesktop_dbus_introspection_call_introspect_finish (
    MyExampleOrgFreedesktopDBusIntrospection *proxy,
    gchar **out_data,
    GAsyncResult *res,
    GError **error);

gboolean my_example_org_freedesktop_dbus_introspection_call_introspect_sync (
    MyExampleOrgFreedesktopDBusIntrospection *proxy,
    gchar **out_data,
    GCancellable *cancellable,
    GError **error);



/* ---- */

#define MY_EXAMPLE_TYPE_ORG_FREEDESKTOP_DBUS_INTROSPECTION_PROXY (my_example_org_freedesktop_dbus_introspection_proxy_get_type ())
#define MY_EXAMPLE_ORG_FREEDESKTOP_DBUS_INTROSPECTION_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), MY_EXAMPLE_TYPE_ORG_FREEDESKTOP_DBUS_INTROSPECTION_PROXY, MyExampleOrgFreedesktopDBusIntrospectionProxy))
#define MY_EXAMPLE_ORG_FREEDESKTOP_DBUS_INTROSPECTION_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), MY_EXAMPLE_TYPE_ORG_FREEDESKTOP_DBUS_INTROSPECTION_PROXY, MyExampleOrgFreedesktopDBusIntrospectionProxyClass))
#define MY_EXAMPLE_ORG_FREEDESKTOP_DBUS_INTROSPECTION_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), MY_EXAMPLE_TYPE_ORG_FREEDESKTOP_DBUS_INTROSPECTION_PROXY, MyExampleOrgFreedesktopDBusIntrospectionProxyClass))
#define MY_EXAMPLE_IS_ORG_FREEDESKTOP_DBUS_INTROSPECTION_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), MY_EXAMPLE_TYPE_ORG_FREEDESKTOP_DBUS_INTROSPECTION_PROXY))
#define MY_EXAMPLE_IS_ORG_FREEDESKTOP_DBUS_INTROSPECTION_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), MY_EXAMPLE_TYPE_ORG_FREEDESKTOP_DBUS_INTROSPECTION_PROXY))

typedef struct _MyExampleOrgFreedesktopDBusIntrospectionProxy MyExampleOrgFreedesktopDBusIntrospectionProxy;
typedef struct _MyExampleOrgFreedesktopDBusIntrospectionProxyClass MyExampleOrgFreedesktopDBusIntrospectionProxyClass;
typedef struct _MyExampleOrgFreedesktopDBusIntrospectionProxyPrivate MyExampleOrgFreedesktopDBusIntrospectionProxyPrivate;

struct _MyExampleOrgFreedesktopDBusIntrospectionProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  MyExampleOrgFreedesktopDBusIntrospectionProxyPrivate *priv;
};

struct _MyExampleOrgFreedesktopDBusIntrospectionProxyClass
{
  GDBusProxyClass parent_class;
};

GType my_example_org_freedesktop_dbus_introspection_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (MyExampleOrgFreedesktopDBusIntrospectionProxy, g_object_unref)
#endif

void my_example_org_freedesktop_dbus_introspection_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
MyExampleOrgFreedesktopDBusIntrospection *my_example_org_freedesktop_dbus_introspection_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
MyExampleOrgFreedesktopDBusIntrospection *my_example_org_freedesktop_dbus_introspection_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void my_example_org_freedesktop_dbus_introspection_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
MyExampleOrgFreedesktopDBusIntrospection *my_example_org_freedesktop_dbus_introspection_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
MyExampleOrgFreedesktopDBusIntrospection *my_example_org_freedesktop_dbus_introspection_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define MY_EXAMPLE_TYPE_ORG_FREEDESKTOP_DBUS_INTROSPECTION_SKELETON (my_example_org_freedesktop_dbus_introspection_skeleton_get_type ())
#define MY_EXAMPLE_ORG_FREEDESKTOP_DBUS_INTROSPECTION_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), MY_EXAMPLE_TYPE_ORG_FREEDESKTOP_DBUS_INTROSPECTION_SKELETON, MyExampleOrgFreedesktopDBusIntrospectionSkeleton))
#define MY_EXAMPLE_ORG_FREEDESKTOP_DBUS_INTROSPECTION_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), MY_EXAMPLE_TYPE_ORG_FREEDESKTOP_DBUS_INTROSPECTION_SKELETON, MyExampleOrgFreedesktopDBusIntrospectionSkeletonClass))
#define MY_EXAMPLE_ORG_FREEDESKTOP_DBUS_INTROSPECTION_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), MY_EXAMPLE_TYPE_ORG_FREEDESKTOP_DBUS_INTROSPECTION_SKELETON, MyExampleOrgFreedesktopDBusIntrospectionSkeletonClass))
#define MY_EXAMPLE_IS_ORG_FREEDESKTOP_DBUS_INTROSPECTION_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), MY_EXAMPLE_TYPE_ORG_FREEDESKTOP_DBUS_INTROSPECTION_SKELETON))
#define MY_EXAMPLE_IS_ORG_FREEDESKTOP_DBUS_INTROSPECTION_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), MY_EXAMPLE_TYPE_ORG_FREEDESKTOP_DBUS_INTROSPECTION_SKELETON))

typedef struct _MyExampleOrgFreedesktopDBusIntrospectionSkeleton MyExampleOrgFreedesktopDBusIntrospectionSkeleton;
typedef struct _MyExampleOrgFreedesktopDBusIntrospectionSkeletonClass MyExampleOrgFreedesktopDBusIntrospectionSkeletonClass;
typedef struct _MyExampleOrgFreedesktopDBusIntrospectionSkeletonPrivate MyExampleOrgFreedesktopDBusIntrospectionSkeletonPrivate;

struct _MyExampleOrgFreedesktopDBusIntrospectionSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  MyExampleOrgFreedesktopDBusIntrospectionSkeletonPrivate *priv;
};

struct _MyExampleOrgFreedesktopDBusIntrospectionSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType my_example_org_freedesktop_dbus_introspection_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (MyExampleOrgFreedesktopDBusIntrospectionSkeleton, g_object_unref)
#endif

MyExampleOrgFreedesktopDBusIntrospection *my_example_org_freedesktop_dbus_introspection_skeleton_new (void);


/* ------------------------------------------------------------------------ */
/* Declarations for com.AppTrainning.AlarmClock */

#define MY_EXAMPLE_TYPE_COM_APP_TRAINNING_ALARM_CLOCK (my_example_com_app_trainning_alarm_clock_get_type ())
#define MY_EXAMPLE_COM_APP_TRAINNING_ALARM_CLOCK(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), MY_EXAMPLE_TYPE_COM_APP_TRAINNING_ALARM_CLOCK, MyExampleComAppTrainningAlarmClock))
#define MY_EXAMPLE_IS_COM_APP_TRAINNING_ALARM_CLOCK(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), MY_EXAMPLE_TYPE_COM_APP_TRAINNING_ALARM_CLOCK))
#define MY_EXAMPLE_COM_APP_TRAINNING_ALARM_CLOCK_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), MY_EXAMPLE_TYPE_COM_APP_TRAINNING_ALARM_CLOCK, MyExampleComAppTrainningAlarmClockIface))

struct _MyExampleComAppTrainningAlarmClock;
typedef struct _MyExampleComAppTrainningAlarmClock MyExampleComAppTrainningAlarmClock;
typedef struct _MyExampleComAppTrainningAlarmClockIface MyExampleComAppTrainningAlarmClockIface;

struct _MyExampleComAppTrainningAlarmClockIface
{
  GTypeInterface parent_iface;


  gboolean (*handle_get_alarm_status) (
    MyExampleComAppTrainningAlarmClock *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_set_alarm_status) (
    MyExampleComAppTrainningAlarmClock *object,
    GDBusMethodInvocation *invocation,
    gint arg_status);

  gboolean (*handle_set_alarm_time) (
    MyExampleComAppTrainningAlarmClock *object,
    GDBusMethodInvocation *invocation,
    gint arg_hour,
    gint arg_min);

  gboolean (*handle_set_time) (
    MyExampleComAppTrainningAlarmClock *object,
    GDBusMethodInvocation *invocation,
    gint arg_hour,
    gint arg_min);

  void (*ring_alarm) (
    MyExampleComAppTrainningAlarmClock *object);

};

GType my_example_com_app_trainning_alarm_clock_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *my_example_com_app_trainning_alarm_clock_interface_info (void);
guint my_example_com_app_trainning_alarm_clock_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void my_example_com_app_trainning_alarm_clock_complete_set_time (
    MyExampleComAppTrainningAlarmClock *object,
    GDBusMethodInvocation *invocation,
    const gchar *return_message);

void my_example_com_app_trainning_alarm_clock_complete_set_alarm_time (
    MyExampleComAppTrainningAlarmClock *object,
    GDBusMethodInvocation *invocation,
    const gchar *return_message);

void my_example_com_app_trainning_alarm_clock_complete_get_alarm_status (
    MyExampleComAppTrainningAlarmClock *object,
    GDBusMethodInvocation *invocation,
    const gchar *status_message);

void my_example_com_app_trainning_alarm_clock_complete_set_alarm_status (
    MyExampleComAppTrainningAlarmClock *object,
    GDBusMethodInvocation *invocation,
    const gchar *return_message);



/* D-Bus signal emissions functions: */
void my_example_com_app_trainning_alarm_clock_emit_ring_alarm (
    MyExampleComAppTrainningAlarmClock *object);



/* D-Bus method calls: */
void my_example_com_app_trainning_alarm_clock_call_set_time (
    MyExampleComAppTrainningAlarmClock *proxy,
    gint arg_hour,
    gint arg_min,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean my_example_com_app_trainning_alarm_clock_call_set_time_finish (
    MyExampleComAppTrainningAlarmClock *proxy,
    gchar **out_return_message,
    GAsyncResult *res,
    GError **error);

gboolean my_example_com_app_trainning_alarm_clock_call_set_time_sync (
    MyExampleComAppTrainningAlarmClock *proxy,
    gint arg_hour,
    gint arg_min,
    gchar **out_return_message,
    GCancellable *cancellable,
    GError **error);

void my_example_com_app_trainning_alarm_clock_call_set_alarm_time (
    MyExampleComAppTrainningAlarmClock *proxy,
    gint arg_hour,
    gint arg_min,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean my_example_com_app_trainning_alarm_clock_call_set_alarm_time_finish (
    MyExampleComAppTrainningAlarmClock *proxy,
    gchar **out_return_message,
    GAsyncResult *res,
    GError **error);

gboolean my_example_com_app_trainning_alarm_clock_call_set_alarm_time_sync (
    MyExampleComAppTrainningAlarmClock *proxy,
    gint arg_hour,
    gint arg_min,
    gchar **out_return_message,
    GCancellable *cancellable,
    GError **error);

void my_example_com_app_trainning_alarm_clock_call_get_alarm_status (
    MyExampleComAppTrainningAlarmClock *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean my_example_com_app_trainning_alarm_clock_call_get_alarm_status_finish (
    MyExampleComAppTrainningAlarmClock *proxy,
    gchar **out_status_message,
    GAsyncResult *res,
    GError **error);

gboolean my_example_com_app_trainning_alarm_clock_call_get_alarm_status_sync (
    MyExampleComAppTrainningAlarmClock *proxy,
    gchar **out_status_message,
    GCancellable *cancellable,
    GError **error);

void my_example_com_app_trainning_alarm_clock_call_set_alarm_status (
    MyExampleComAppTrainningAlarmClock *proxy,
    gint arg_status,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean my_example_com_app_trainning_alarm_clock_call_set_alarm_status_finish (
    MyExampleComAppTrainningAlarmClock *proxy,
    gchar **out_return_message,
    GAsyncResult *res,
    GError **error);

gboolean my_example_com_app_trainning_alarm_clock_call_set_alarm_status_sync (
    MyExampleComAppTrainningAlarmClock *proxy,
    gint arg_status,
    gchar **out_return_message,
    GCancellable *cancellable,
    GError **error);



/* ---- */

#define MY_EXAMPLE_TYPE_COM_APP_TRAINNING_ALARM_CLOCK_PROXY (my_example_com_app_trainning_alarm_clock_proxy_get_type ())
#define MY_EXAMPLE_COM_APP_TRAINNING_ALARM_CLOCK_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), MY_EXAMPLE_TYPE_COM_APP_TRAINNING_ALARM_CLOCK_PROXY, MyExampleComAppTrainningAlarmClockProxy))
#define MY_EXAMPLE_COM_APP_TRAINNING_ALARM_CLOCK_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), MY_EXAMPLE_TYPE_COM_APP_TRAINNING_ALARM_CLOCK_PROXY, MyExampleComAppTrainningAlarmClockProxyClass))
#define MY_EXAMPLE_COM_APP_TRAINNING_ALARM_CLOCK_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), MY_EXAMPLE_TYPE_COM_APP_TRAINNING_ALARM_CLOCK_PROXY, MyExampleComAppTrainningAlarmClockProxyClass))
#define MY_EXAMPLE_IS_COM_APP_TRAINNING_ALARM_CLOCK_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), MY_EXAMPLE_TYPE_COM_APP_TRAINNING_ALARM_CLOCK_PROXY))
#define MY_EXAMPLE_IS_COM_APP_TRAINNING_ALARM_CLOCK_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), MY_EXAMPLE_TYPE_COM_APP_TRAINNING_ALARM_CLOCK_PROXY))

typedef struct _MyExampleComAppTrainningAlarmClockProxy MyExampleComAppTrainningAlarmClockProxy;
typedef struct _MyExampleComAppTrainningAlarmClockProxyClass MyExampleComAppTrainningAlarmClockProxyClass;
typedef struct _MyExampleComAppTrainningAlarmClockProxyPrivate MyExampleComAppTrainningAlarmClockProxyPrivate;

struct _MyExampleComAppTrainningAlarmClockProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  MyExampleComAppTrainningAlarmClockProxyPrivate *priv;
};

struct _MyExampleComAppTrainningAlarmClockProxyClass
{
  GDBusProxyClass parent_class;
};

GType my_example_com_app_trainning_alarm_clock_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (MyExampleComAppTrainningAlarmClockProxy, g_object_unref)
#endif

void my_example_com_app_trainning_alarm_clock_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
MyExampleComAppTrainningAlarmClock *my_example_com_app_trainning_alarm_clock_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
MyExampleComAppTrainningAlarmClock *my_example_com_app_trainning_alarm_clock_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void my_example_com_app_trainning_alarm_clock_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
MyExampleComAppTrainningAlarmClock *my_example_com_app_trainning_alarm_clock_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
MyExampleComAppTrainningAlarmClock *my_example_com_app_trainning_alarm_clock_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define MY_EXAMPLE_TYPE_COM_APP_TRAINNING_ALARM_CLOCK_SKELETON (my_example_com_app_trainning_alarm_clock_skeleton_get_type ())
#define MY_EXAMPLE_COM_APP_TRAINNING_ALARM_CLOCK_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), MY_EXAMPLE_TYPE_COM_APP_TRAINNING_ALARM_CLOCK_SKELETON, MyExampleComAppTrainningAlarmClockSkeleton))
#define MY_EXAMPLE_COM_APP_TRAINNING_ALARM_CLOCK_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), MY_EXAMPLE_TYPE_COM_APP_TRAINNING_ALARM_CLOCK_SKELETON, MyExampleComAppTrainningAlarmClockSkeletonClass))
#define MY_EXAMPLE_COM_APP_TRAINNING_ALARM_CLOCK_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), MY_EXAMPLE_TYPE_COM_APP_TRAINNING_ALARM_CLOCK_SKELETON, MyExampleComAppTrainningAlarmClockSkeletonClass))
#define MY_EXAMPLE_IS_COM_APP_TRAINNING_ALARM_CLOCK_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), MY_EXAMPLE_TYPE_COM_APP_TRAINNING_ALARM_CLOCK_SKELETON))
#define MY_EXAMPLE_IS_COM_APP_TRAINNING_ALARM_CLOCK_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), MY_EXAMPLE_TYPE_COM_APP_TRAINNING_ALARM_CLOCK_SKELETON))

typedef struct _MyExampleComAppTrainningAlarmClockSkeleton MyExampleComAppTrainningAlarmClockSkeleton;
typedef struct _MyExampleComAppTrainningAlarmClockSkeletonClass MyExampleComAppTrainningAlarmClockSkeletonClass;
typedef struct _MyExampleComAppTrainningAlarmClockSkeletonPrivate MyExampleComAppTrainningAlarmClockSkeletonPrivate;

struct _MyExampleComAppTrainningAlarmClockSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  MyExampleComAppTrainningAlarmClockSkeletonPrivate *priv;
};

struct _MyExampleComAppTrainningAlarmClockSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType my_example_com_app_trainning_alarm_clock_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (MyExampleComAppTrainningAlarmClockSkeleton, g_object_unref)
#endif

MyExampleComAppTrainningAlarmClock *my_example_com_app_trainning_alarm_clock_skeleton_new (void);


/* ---- */

#define MY_EXAMPLE_TYPE_OBJECT (my_example_object_get_type ())
#define MY_EXAMPLE_OBJECT(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), MY_EXAMPLE_TYPE_OBJECT, MyExampleObject))
#define MY_EXAMPLE_IS_OBJECT(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), MY_EXAMPLE_TYPE_OBJECT))
#define MY_EXAMPLE_OBJECT_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), MY_EXAMPLE_TYPE_OBJECT, MyExampleObject))

struct _MyExampleObject;
typedef struct _MyExampleObject MyExampleObject;
typedef struct _MyExampleObjectIface MyExampleObjectIface;

struct _MyExampleObjectIface
{
  GTypeInterface parent_iface;
};

GType my_example_object_get_type (void) G_GNUC_CONST;

MyExampleOrgFreedesktopDBusIntrospection *my_example_object_get_org_freedesktop_dbus_introspection (MyExampleObject *object);
MyExampleComAppTrainningAlarmClock *my_example_object_get_com_app_trainning_alarm_clock (MyExampleObject *object);
MyExampleOrgFreedesktopDBusIntrospection *my_example_object_peek_org_freedesktop_dbus_introspection (MyExampleObject *object);
MyExampleComAppTrainningAlarmClock *my_example_object_peek_com_app_trainning_alarm_clock (MyExampleObject *object);

#define MY_EXAMPLE_TYPE_OBJECT_PROXY (my_example_object_proxy_get_type ())
#define MY_EXAMPLE_OBJECT_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), MY_EXAMPLE_TYPE_OBJECT_PROXY, MyExampleObjectProxy))
#define MY_EXAMPLE_OBJECT_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), MY_EXAMPLE_TYPE_OBJECT_PROXY, MyExampleObjectProxyClass))
#define MY_EXAMPLE_OBJECT_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), MY_EXAMPLE_TYPE_OBJECT_PROXY, MyExampleObjectProxyClass))
#define MY_EXAMPLE_IS_OBJECT_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), MY_EXAMPLE_TYPE_OBJECT_PROXY))
#define MY_EXAMPLE_IS_OBJECT_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), MY_EXAMPLE_TYPE_OBJECT_PROXY))

typedef struct _MyExampleObjectProxy MyExampleObjectProxy;
typedef struct _MyExampleObjectProxyClass MyExampleObjectProxyClass;
typedef struct _MyExampleObjectProxyPrivate MyExampleObjectProxyPrivate;

struct _MyExampleObjectProxy
{
  /*< private >*/
  GDBusObjectProxy parent_instance;
  MyExampleObjectProxyPrivate *priv;
};

struct _MyExampleObjectProxyClass
{
  GDBusObjectProxyClass parent_class;
};

GType my_example_object_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (MyExampleObjectProxy, g_object_unref)
#endif

MyExampleObjectProxy *my_example_object_proxy_new (GDBusConnection *connection, const gchar *object_path);

#define MY_EXAMPLE_TYPE_OBJECT_SKELETON (my_example_object_skeleton_get_type ())
#define MY_EXAMPLE_OBJECT_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), MY_EXAMPLE_TYPE_OBJECT_SKELETON, MyExampleObjectSkeleton))
#define MY_EXAMPLE_OBJECT_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), MY_EXAMPLE_TYPE_OBJECT_SKELETON, MyExampleObjectSkeletonClass))
#define MY_EXAMPLE_OBJECT_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), MY_EXAMPLE_TYPE_OBJECT_SKELETON, MyExampleObjectSkeletonClass))
#define MY_EXAMPLE_IS_OBJECT_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), MY_EXAMPLE_TYPE_OBJECT_SKELETON))
#define MY_EXAMPLE_IS_OBJECT_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), MY_EXAMPLE_TYPE_OBJECT_SKELETON))

typedef struct _MyExampleObjectSkeleton MyExampleObjectSkeleton;
typedef struct _MyExampleObjectSkeletonClass MyExampleObjectSkeletonClass;
typedef struct _MyExampleObjectSkeletonPrivate MyExampleObjectSkeletonPrivate;

struct _MyExampleObjectSkeleton
{
  /*< private >*/
  GDBusObjectSkeleton parent_instance;
  MyExampleObjectSkeletonPrivate *priv;
};

struct _MyExampleObjectSkeletonClass
{
  GDBusObjectSkeletonClass parent_class;
};

GType my_example_object_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (MyExampleObjectSkeleton, g_object_unref)
#endif

MyExampleObjectSkeleton *my_example_object_skeleton_new (const gchar *object_path);
void my_example_object_skeleton_set_org_freedesktop_dbus_introspection (MyExampleObjectSkeleton *object, MyExampleOrgFreedesktopDBusIntrospection *interface_);
void my_example_object_skeleton_set_com_app_trainning_alarm_clock (MyExampleObjectSkeleton *object, MyExampleComAppTrainningAlarmClock *interface_);

/* ---- */

#define MY_EXAMPLE_TYPE_OBJECT_MANAGER_CLIENT (my_example_object_manager_client_get_type ())
#define MY_EXAMPLE_OBJECT_MANAGER_CLIENT(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), MY_EXAMPLE_TYPE_OBJECT_MANAGER_CLIENT, MyExampleObjectManagerClient))
#define MY_EXAMPLE_OBJECT_MANAGER_CLIENT_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), MY_EXAMPLE_TYPE_OBJECT_MANAGER_CLIENT, MyExampleObjectManagerClientClass))
#define MY_EXAMPLE_OBJECT_MANAGER_CLIENT_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), MY_EXAMPLE_TYPE_OBJECT_MANAGER_CLIENT, MyExampleObjectManagerClientClass))
#define MY_EXAMPLE_IS_OBJECT_MANAGER_CLIENT(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), MY_EXAMPLE_TYPE_OBJECT_MANAGER_CLIENT))
#define MY_EXAMPLE_IS_OBJECT_MANAGER_CLIENT_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), MY_EXAMPLE_TYPE_OBJECT_MANAGER_CLIENT))

typedef struct _MyExampleObjectManagerClient MyExampleObjectManagerClient;
typedef struct _MyExampleObjectManagerClientClass MyExampleObjectManagerClientClass;
typedef struct _MyExampleObjectManagerClientPrivate MyExampleObjectManagerClientPrivate;

struct _MyExampleObjectManagerClient
{
  /*< private >*/
  GDBusObjectManagerClient parent_instance;
  MyExampleObjectManagerClientPrivate *priv;
};

struct _MyExampleObjectManagerClientClass
{
  GDBusObjectManagerClientClass parent_class;
};

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (MyExampleObjectManagerClient, g_object_unref)
#endif

GType my_example_object_manager_client_get_type (void) G_GNUC_CONST;

GType my_example_object_manager_client_get_proxy_type (GDBusObjectManagerClient *manager, const gchar *object_path, const gchar *interface_name, gpointer user_data);

void my_example_object_manager_client_new (
    GDBusConnection        *connection,
    GDBusObjectManagerClientFlags  flags,
    const gchar            *name,
    const gchar            *object_path,
    GCancellable           *cancellable,
    GAsyncReadyCallback     callback,
    gpointer                user_data);
GDBusObjectManager *my_example_object_manager_client_new_finish (
    GAsyncResult        *res,
    GError             **error);
GDBusObjectManager *my_example_object_manager_client_new_sync (
    GDBusConnection        *connection,
    GDBusObjectManagerClientFlags  flags,
    const gchar            *name,
    const gchar            *object_path,
    GCancellable           *cancellable,
    GError                **error);

void my_example_object_manager_client_new_for_bus (
    GBusType                bus_type,
    GDBusObjectManagerClientFlags  flags,
    const gchar            *name,
    const gchar            *object_path,
    GCancellable           *cancellable,
    GAsyncReadyCallback     callback,
    gpointer                user_data);
GDBusObjectManager *my_example_object_manager_client_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
GDBusObjectManager *my_example_object_manager_client_new_for_bus_sync (
    GBusType                bus_type,
    GDBusObjectManagerClientFlags  flags,
    const gchar            *name,
    const gchar            *object_path,
    GCancellable           *cancellable,
    GError                **error);


G_END_DECLS

#endif /* __SRC_MYAPP_GENERATED_H__ */
